dekorate:
  capability:
    category: "database"
    kind: "postgres"
    version: "10"
    parameters:
      - name: "DB_USER"
        value: "admin"
      - name: "DB_PASSWORD"
        value: "admin"
      - name: "DB_NAME"
        value: "sample-db"


