# Endpoint property to access the backend microservice
endpoint:
  fruit: ${ENDPOINT_BACKEND}

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    deploymentMode: "dev"
