# TODO: Check how we could specify such securty context
# oc adm policy add-scc-to-user privileged -z postgres-db
apiVersion: halkyon.io/v1beta1
kind: Capability
metadata:
  name: postgres-db
spec:
  category: database
  kind: postgres
  version: "10"
  parameters:
  # This parameter DB_CONFIG_NAME is added automatically by the Operator. No need to add it.
  # It is calculated using the Capability name + "-config"
  # It has been added to document
  - name: DB_CONFIG_NAME
    value: postgres-db-config
  # This parameter DB_HOST is added automatically by the Operator. No need to add it.
  # It is calculated using the Capability name
  - name: DB_HOST
    value: postgres-db
  # This parameter DB_PORT is added automatically by the Operator. No need to add it.
  # It is calculated according to the default service port used by the database.
  - name: DB_PORT
    value: "5324"
  # This parameter DB_NAME is used to define the database to be created. No need to add it.
  # It is added automatically by the Operator and is equal to sample-db
  - name: DB_NAME
    value: sample-db
  # This parameter DB_USER is used to define the credentials of the user to access the DB. No need to add it.
  # It is added automatically by the Operator and is equal to admin
  - name: DB_USER
    value: admin
  # This parameter DB_PASSWORD is used to define the credentials of the user to access the DB. No need to add it.
  # It is added automatically by the Operator and is equal to admin
  - name: DB_PASSWORD
    value: admin
