#
# TODO: TO be documented that we must configure such security rules on openshift
# oc adm policy add-scc-to-user privileged -z build-bot
# oc adm policy add-role-to-user edit -z build-bot
#
#
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: fruit-backend-sb
spec:
  deploymentMode: build
  port: 8080
  buildConfig:
    type: "s2i"
    url: "https://github.com/halkyonio/operator.git"
    ref: "master"
    contextPath: "demo/"
    moduleDirName: "fruit-backend-sb"
  runtime: spring-boot
  version: 2.1.6